services:
  guacenc:
    image: tancou/guacenc:latest
    build:
      context: .
      dockerfile: Dockerfile
#    restart: always
    volumes:
      - ./record:/record
    environment:
      - AUTOCONVERT=false
      - AUTOCONVERT_WAIT=60
